### ISSUE TITLE
Expand all fields for current bookmarks?

### ISSUE THREAD

**Issue by Gittyperson** [JustOff/add-bookmark-helper#1]
Many thanks for your fantastic fork.

When using the Library to browse/edit current bookmarks, I always press the "More" button to reveal Keyword/Description. Perhaps I'm missing something but I couldn't find a way to have this permanently expanded for existing bookmarks. I guess the Ctrl-D dialog is separate from the Ctrl-Shift-B ones.

By the way, it'd be cool for Options/Panel to also apply for this "Edit Bookmark" dialog in the Library, and not just the New/Edit this Bookmark dialog.

**Comment by JustOff** [comment]
Sorry, but the Library enhancement is outside the scope of this extension.
