### ISSUE TITLE
Allow to add Duplicate Bookmarks

### ISSUE THREAD

**Issue by billmcct** [JustOff/add-bookmark-helper#2]
Would it be possible to allow duplicate bookmarks the same way "Add Bookmark Here ²" worked?
I have a daily need for duplicate bookmarks, actually many times a day, so if it would be possible to change this it would be most appreciated.
Thanks,
Bill

**Comment by JustOff** [comment]
> the same way "Add Bookmark Here ²" worked

Could you please provide more details?

**Comment by billmcct** [comment]
"Add Bookmark Here" had a checkbox in the options to allow or disallow duplicate bookmarks.
"Add Bookmark Helper" doesn't have that option. It wont allow duplicates by default. I have to copy and paste to get the duplicates.
Bill

**Comment by JustOff** [comment]
Well, this option [was added to the original add-on](http://forums.mozillazine.org/viewtopic.php?p=14325293#p14325293) later than I forked it, I have to look closer at how to backport it.

**Comment by billmcct** [comment]
I didn't realize it was added after. Thanks for looking into this.
Bill

**Comment by JustOff** [comment]
Here is the [beta version](https://github.com/JustOff/add-bookmark-helper/releases/download/1.0.1/add-bookmark-helper-1.0.5b1.xpi) for testing, please check if this new option does not cause any negative side effects.

**Comment by billmcct** [comment]
Sorry for taking so long, had a Doctors appointment.
With the box checked to allow duplicates it still want allow duplicates. If trying to add a duplicate to a different folder the original is deleted, or maybe just moved which is the original way it worked.

**Comment by JustOff** [comment]
How exactly are you trying to add a bookmark to another folder? You can't just use the "star button" for this, but only "Add Bookmark Here..." from the context menu on the folder where you want to place a copy of the bookmark. The original extension works the same way.

**Comment by billmcct** [comment]
From the right click menu "bookmark this page"
Ok I see what I was doing wrong.
Thanks, I can add duplicates now.

**Comment by billmcct** [comment]
Sorry for putting you through all that. I guess I'm just getting too old to remember things.
Should I revert to the old version or are you going to release the beta?
Bill

**Comment by JustOff** [comment]
If you want these changes to be included into the next release, please take time to check if they not cause any negative side effects.

**Comment by billmcct** [comment]
Well for some reason it will no longer allow duplicates. Right clicking a folder and selecting add bookmark here opens the bookmarks dialog and and then if selecting a different folder it moves the bookmark. What am I doing wrong here?

**Comment by billmcct** [comment]
OK, sorry. I restarted PM and it works correctly again.  I have not found any adverse interactions with any other extensions.

**Comment by JustOff** [comment]
Thanks for the feedback. I installed this version on my main workplace, and if everything goes well, I'll release it in a few days.

**Comment by JustOff** [comment]
Resolved by [ABH 1.0.5](https://github.com/JustOff/add-bookmark-helper/releases/tag/1.0.5).

**Comment by JustOff** [comment]
It turned out [at least one error](https://github.com/JustOff/add-bookmark-helper/issues/3) was missed when testing the beta :confused:

**Comment by billmcct** [comment]
What would that be? I still have not found anything wrong.
Bill

**Comment by JustOff** [comment]
There was an empty name field when you click "Bookmark This Link" from the context menu:

![2019-02-22_14-46-58](https://user-images.githubusercontent.com/340855/53243563-f12e5400-36b0-11e9-8fab-579f5ee3182f.png)

We are both missed that)

**Comment by billmcct** [comment]
Your right. I rarely ever bookmark a link so it could have been a while before I noticed it.
