### ISSUE TITLE
Bookmark This Link: no bookmark name?

### ISSUE THREAD

**Issue by Gittyperson** [JustOff/add-bookmark-helper#3]
Right-click a link, then select "Bookmark This Link". The 'Name' field is blank in the 'Page Bookmarked' popup. Clicking 'Done' saves the bookmark with the URL as its name.

It's been some time since I've used Add Bookmark Helper but I don't remember this strange behaviour. Disabling it makes the name appear normally. Also tried disabling all other extensions.

PM 28.4.0 x64, W10, ABH 1.0.5

**Comment by Gittyperson** [comment]
Issue is not present in 1.0.4, but it seems ABH is not 'activated' when bookmarking links in 1.0.4?

**Comment by JustOff** [comment]
Sorry, this was a regression. Fixed by [ABH 1.0.6](https://github.com/JustOff/add-bookmark-helper/releases/tag/1.0.6).
