### ISSUE TITLE
Is it possible to create version compatible with Waterfox Classic?

### ISSUE THREAD

**Issue by SylwesterZarebski** [JustOff/add-bookmark-helper#4]
Current version of this addon supports only Palemoon, but i'm currently testing Waterfox Classic 2020 (56) and this addon is not compatible with it.

Is it possible to make version compatible with Waterfox?

**Comment by JustOff** [comment]
Unfortunately Pale Moon and Waterfox are too different. You should try [Add Bookmark Here ²](https://web.archive.org/web/20181005154949/https://addons.mozilla.org/en-US/firefox/addon/add-bookmark-here-2/). The binaries can be found in [Classic Add-ons Archive](https://github.com/JustOff/ca-archive).

**Comment by SylwesterZarebski** [comment]
Thanks, but Add Bookmark Here² is not working on versions later than 55.

**Comment by JustOff** [comment]
Then I'm afraid that someone should fork and adapt it specifically for Waterfox.
