### ISSUE TITLE
Stopped working in recent builds of NM27-SSE

### ISSUE THREAD

**Issue by temp10min** [JustOff/add-bookmark-helper#6]
I'm not sure if this is a regression in the browser, or a bug in the extension that didn't manifest itself before. Therefore i report to both.
Last working browser build - https://o.rths.ml/palemoon/palemoon-27.9.7.win32-git-20200704-32e7e53ea-xpmod-sse.7z (you can browse that folder for other versions).
In newer builds the extension fails to do most of its functions. The options dialog is accessible, but none of the settings have any effect.
Changelog for the first non-working build available at https://msfn.org/board/topic/180462-my-browser-builds-part-2/?do=findComment&comment=1184100

**Comment by JustOff** [comment]
Sorry, but I don't support unofficial builds based on PM27.
