### ISSUE TITLE
pop up warning persists 

### ISSUE THREAD

**Issue by wavyhub** [JustOff/add-bookmark-helper#8]
Add Bookmark Helper 1.0.9
pop up warning persists on restart after checking box

**Comment by JustOff** [comment]
In order to completely dismiss the migration warning you should check the box and press `Cancel`.
You can also manually set `extensions.justoff-migration` to `false` using `about:config`.

**Comment by wavyhub** [comment]
In order to completely dismiss the migration warning you should check the box and press Cancel.
If that was working I would not have opened an ISSUE. I will try the edit 
Thanks for your works and stay safe
